/**
 * Helper functions go here
 */

import Promise from 'bluebird'
import path from 'path'
import fs from 'fs'
import { output } from '../webpack.config.js'

const readdir = Promise.promisify(fs.readdir)

/**
 * Get the js bundle file url generated by webpack
 * @return {string} Url of the js bundle file
 *
 * FIXME This works now since bundle file is locally stored
 * FIXME Need revisit once bundle file is deployed to CDN
 */
export const getJsUrl = (function () {
  let cached

  return async function () {
    if (!cached) {
      const folder = path.resolve(__dirname, '..', output.path)
      const files = await readdir(folder)
      cached = '/js/' + files.find(file => /^bundle\..*js$/.test(file))
    }
    return cached
  }
})()
